<a href="https://colab.research.google.com/github/Akshara-j8/AIML-COURSE-IITH/blob/main/Basics_of_Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import matplotlib.pyplot as plt
a=[[1,2,3,4],[5,6,7,8]]
b=np.transpose(a)
print('a',a)
print('b',b)

a [[1, 2, 3, 4], [5, 6, 7, 8]]
b [[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [ ]:
print("matrix and its transpose")
a=np.array([[1,2,3],[8,9,10]])
b=a.T
print('a\n',a)
print('b\n',b)

matrix and its transpose
a
 [[ 1  2  3]
 [ 8  9 10]]
b
 [[ 1  8]
 [ 2  9]
 [ 3 10]]


In [ ]:
a=3
b=9
z=np.dot(a,b)
print(z)

27


In [ ]:
z=a*b
print(z)

27


In [ ]:
a=np.array([1,2,3]) #1d array
b=[3,4,5]
c=np.dot(a,b) #scalar
print(c)

26


In [ ]:
a=[[1,2,3],[2,3,4],[3,4,5]] #2d array
b=[[3,4,5],[2,3,4],[1,2,3]]
c=np.dot(a,b) #matrix multiplication
print(c)

[[10 16 22]
 [16 25 34]
 [22 34 46]]


In [ ]:
z=np.matmul(a,b)
print(z)

[[10 16 22]
 [16 25 34]
 [22 34 46]]


In [ ]:
 newa = np.array(a)
 newb = np.array(b)
 z = newa.dot(newb)
 print(z)

[[10 16 22]
 [16 25 34]
 [22 34 46]]


In [ ]:
%%time
 a = np.random.randint(-5,4,(500,5))
 b = np.random.randint(-4,5,(5,1000))
 c = np.random.randint(-9,4,(1000,10))
 d = np.random.randint(-2,5,(10,2000))
 e = np.random.randint(-4,9,(2000,200))
 z = np.linalg.multi_dot([a,b,c,d,e])
 print(z)

[[-39453850 -40931381 -37184295 ... -38815776 -39507897 -38925017]
 [-24198777 -23304390 -23185326 ... -22678616 -23837172 -24400729]
 [-70730219 -72298572 -68149745 ... -69876751 -72669553 -72092955]
 ...
 [-45244769 -46334228 -42709600 ... -44384103 -46053590 -46697620]
 [-15040864 -12299321 -13612499 ... -12366278 -14059025 -17092241]
 [ 25242426  26730241  25837847 ...  26316150  27604273  26033283]]
CPU times: user 11.8 ms, sys: 945 µs, total: 12.7 ms
Wall time: 12.4 ms


In [ ]:
%%time
z = a.dot(b).dot(c).dot(d).dot(e)
print(z)

[[-39453850 -40931381 -37184295 ... -38815776 -39507897 -38925017]
 [-24198777 -23304390 -23185326 ... -22678616 -23837172 -24400729]
 [-70730219 -72298572 -68149745 ... -69876751 -72669553 -72092955]
 ...
 [-45244769 -46334228 -42709600 ... -44384103 -46053590 -46697620]
 [-15040864 -12299321 -13612499 ... -12366278 -14059025 -17092241]
 [ 25242426  26730241  25837847 ...  26316150  27604273  26033283]]
CPU times: user 295 ms, sys: 10.4 ms, total: 305 ms
Wall time: 304 ms


**Observe the CPU time that multi_dot consumes as against CPU time that successive dot methods consume to arrive at the same solution. Which one is more efficient, why ?**
* the cpu time that multi_dot consumes is less comparred to the cpu time that dot method consumes
multi_dot is more efficient because it takes less time and gives faster response

In [ ]:
a=np.array([[1,2,3],[2,3,4]])
b=np.array([5,6,7])
c=np.inner(a,b)
print(c)

[38 56]


In [ ]:
d=np.outer(a,b)
print(d)

[[ 5  6  7]
 [10 12 14]
 [15 18 21]
 [10 12 14]
 [15 18 21]
 [20 24 28]]


In [ ]:
a=np.random.random([3,6,5])
b=np.random.random([3,5,6])
c=a@b
print(c)
print(c.shape)

[[[1.84150414 1.31017967 1.31685505 1.3091504  0.53518889 1.78366234]
  [1.61299261 0.60020571 0.99204001 1.10406631 0.48368412 1.32116783]
  [1.39570015 0.96503445 1.02303364 0.98482222 0.47502973 1.46873519]
  [1.57674987 0.74898102 1.13310016 1.10400832 0.57198187 1.60784879]
  [0.94196015 0.68266906 0.37589521 0.59347529 0.30731038 0.56844808]
  [1.38739814 0.75344385 0.74796911 0.94188827 0.28345091 0.92306917]]

 [[1.09682098 0.85559446 1.70934397 2.12870263 1.30956354 1.67485181]
  [0.92663988 0.93202968 1.76940323 1.81135016 1.2953005  1.67331228]
  [0.36538699 0.26177109 0.773125   0.71416055 0.28626658 0.67676089]
  [0.7842307  0.29588825 0.9081351  1.22175053 0.62688393 0.7601349 ]
  [1.10199849 0.35546001 1.25569931 1.49654593 0.60203131 0.96132974]
  [0.73532141 0.58102851 1.59549174 1.47538984 0.75818198 1.40035546]]

 [[0.92805536 0.82966637 0.59383362 1.29161203 0.9617892  1.40933106]
  [0.92787331 0.67192163 0.92184737 1.03520457 0.97288404 1.30748244]
  [1.65488956 1.

In [ ]:
a=np.arange(9).reshape(3,3)
eig_val,eig_vec=np.linalg.eig(a)
print("values are",eig_val)
print("vector\n",eig_vec)

values are [ 1.33484692e+01 -1.34846923e+00 -2.48477279e-16]
vector
 [[ 0.16476382  0.79969966  0.40824829]
 [ 0.50577448  0.10420579 -0.81649658]
 [ 0.84678513 -0.59128809  0.40824829]]


In [ ]:
a=np.arange(9).reshape(3,3)
eignvalues=np.linalg.eigvals(a)
print(eignvalues)

In [ ]:
a=np.eye(4)
b=np.trace(a)
print(b)
print(a)

4.0
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
a = np.arange(12).reshape(4,3)
z = np.linalg.norm(a)
print(a)
print('\n Frobenius Norm of above matrix:')
print(z)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

 Frobenius Norm of above matrix:
22.494443758403985


In [7]:
import numpy as np
a=np.random.randint(1,10,[3,3])
det=np.linalg.det(a)
print(int(det))

-136


In [8]:
inv=np.linalg.inv(a)
print(inv)

[[-0.11764706 -0.32352941  0.33823529]
 [-0.05882353  0.08823529  0.04411765]
 [ 0.35294118  0.47058824 -0.51470588]]


In [9]:
a=np.random.random([4,4])
b=np.linalg.matrix_power(a,2)
c=np.linalg.matrix_power(a,3)
d=np.linalg.matrix_power(a,-1)
e=np.linalg.matrix_power(a,-2)
print("matrix is")
print(a)
print("matrix power 2 is")
print(b)
print("matrix power 3 is")
print(c)
print("matrix power -1 is")
print(d)
print("matrix power -2 is")
print(e)


matrix is
[[0.42138876 0.46383006 0.11077322 0.46327303]
 [0.03334933 0.20024087 0.10273791 0.7494769 ]
 [0.68101539 0.10296547 0.46212801 0.55321004]
 [0.19384549 0.43219441 0.85644079 0.05183921]]
matrix power 2 is
[[0.35827857 0.49996034 0.54228885 0.62814453]
 [0.23597975 0.39006301 0.7136272  0.26121368]
 [0.71235963 0.62317082 0.77337067 0.67699813]
 [0.68939586 0.28704279 0.50605813 0.89020206]]
matrix power 3 is
[[0.65871795 0.59361045 0.87962802 0.87325168]
 [0.64907375 0.37393511 0.61971567 0.80999311]
 [0.97887304 0.82742336 1.08013871 1.26000061]
 [0.81727139 0.81408709 1.10212577 0.86061426]]
matrix power -1 is
[[ 0.86420219 -1.35369252  1.16437884 -0.577678  ]
 [ 2.09254283 -0.27206685 -1.43396371  0.53573893]
 [-1.22558474  0.35785078  0.44372004  1.04378689]
 [-0.4295251   1.41813416  0.27048201 -0.26051256]]
matrix power -2 is
[[-3.26473188 -1.20412021  3.30781142  0.14139937]
 [ 2.7663993  -2.51203456  2.33527589 -2.99089198]
 [-1.30248412  3.20072097 -1.46097693  1.0

In [10]:
a = np.random.randint(1,20,[4,4])
b = np.array([4,9,12,7])
x = np.linalg.solve(a,b)
print('Coefficient Matrix')
print(a)
print('Dependent Variable vector')
print(b)
print('Solution')
print(x)

Coefficient Matrix
[[ 8  7 10 13]
 [19 12  6 15]
 [ 8 19  3  4]
 [ 9  1  4 19]]
Dependent Variable vector
[ 4  9 12  7]
Solution
[-0.21411983  0.70661093 -0.66883418  0.57346338]


In [11]:
B = a.dot(x)
print(B)

[ 4.  9. 12.  7.]


In [18]:
a=[1,2,3,4]
b=[3,4,5,6]
c=[]
d=[]
for i in range(0,len(a)):
  for j in range(0,len(b)):
    if i==j:
     c.append(a[i]+b[j])
     d.append(a[i]-b[j])
print(c)
print(d)

[4, 6, 8, 10]
[-2, -2, -2, -2]


In [22]:
a = [[1, 2, 3], [2, 3, 4]]
rows = len(a)
cols = len(a[0])


b = []

for i in range(cols):
    row = []
    for j in range(rows):
        row.append(a[j][i])
    b.append(row)

print("Transpose of a is:")
print(b)


Transpose of a is:
[[1, 2], [2, 3], [3, 4]]


In [23]:
A = [[1, 2, 3],
     [4, 5, 6]]
B = [[7, 8],
     [9, 10],
     [11, 12]]
result = []
for i in range(len(A)):
    row = []
    for j in range(len(B[0])):
        total = 0
        for k in range(len(B)):
            total += A[i][k] * B[k][j]
        row.append(total)
    result.append(row)
print("Multiplication result:")
for r in result:
    print(r)


Multiplication result:
[58, 64]
[139, 154]


In [24]:
A = [[4, 7],
     [2, 6]]
det = A[0][0]*A[1][1] - A[0][1]*A[1][0]

if det == 0:
    print("Matrix is singular and cannot be inverted.")
else:
    inv = [[A[1][1]/det, -A[0][1]/det],
           [-A[1][0]/det, A[0][0]/det]]

    print("Inverse of A:")
    for row in inv:
        print(row)


Inverse of A:
[0.6, -0.7]
[-0.2, 0.4]
